CREATE SEQUENCE S_FIN_TEST;


CREATE TABLE FIN_TEST (
	SEQTESTE INTEGER NOT NULL DEFAULT NEXTVAL('S_FIN_TEST'),
	USERNAME VARCHAR(255) NOT NULL,
	PASSWORD VARCHAR(255) NOT NULL,
	LASTUPDATE TIMESTAMP
);

ALTER TABLE FIN_TEST
ADD CONSTRAINT PK_FIN_TEST PRIMARY KEY(SEQTESTE);

INSERT INTO FIN_TEST(USERNAME, PASSWORD, LASTUPDATE)
VALUES('DANIEL', '123456', NOW());

SELECT *
FROM FIN_TEST;

